# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d_%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, prefixed by ',' or \n
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to copy from the target metadata's instructions
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow alembic to create empty migrations
# write_empty = false

# logging configuration URL
# log_config_file = alembic.ini

sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:5433/sara_db

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
