"""add_sangam_tables

Revision ID: 08d1adb2e854
Revises: 733514a28521
Create Date: 2026-08-20 12:08:41.008994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08d1adb2e854'
down_revision: Union[str, None] = '733514a28521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('allocated_amount', sa.Float(), nullable=False),
    sa.Column('spent_amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_code')
    )
    op.create_index(op.f('ix_government_projects_category'), 'government_projects', ['category'], unique=False)
    op.create_index(op.f('ix_government_projects_location'), 'government_projects', ['location'], unique=False)
    op.create_index(op.f('ix_government_projects_status'), 'government_projects', ['status'], unique=False)
    op.create_table('need_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('complaint_count', sa.Integer(), nullable=False),
    sa.Column('unique_citizen_count', sa.Integer(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('persistence_score', sa.Float(), nullable=False),
    sa.Column('unresolved_count', sa.Integer(), nullable=False),
    sa.Column('reopened_count', sa.Integer(), nullable=False),
    sa.Column('first_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('priority_breakdown', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_need_clusters_category'), 'need_clusters', ['category'], unique=False)
    op.create_index(op.f('ix_need_clusters_location_name'), 'need_clusters', ['location_name'], unique=False)
    op.create_index(op.f('ix_need_clusters_priority_score'), 'need_clusters', ['priority_score'], unique=False)
    op.create_index(op.f('ix_need_clusters_status'), 'need_clusters', ['status'], unique=False)
    op.create_table('intelligence_alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('need_cluster_id', sa.Uuid(), nullable=True),
    sa.Column('government_project_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['government_project_id'], ['government_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['need_cluster_id'], ['need_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_alerts_government_project_id'), 'intelligence_alerts', ['government_project_id'], unique=False)
    op.create_index(op.f('ix_intelligence_alerts_need_cluster_id'), 'intelligence_alerts', ['need_cluster_id'], unique=False)
    op.create_index(op.f('ix_intelligence_alerts_severity'), 'intelligence_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_intelligence_alerts_status'), 'intelligence_alerts', ['status'], unique=False)
    op.create_index(op.f('ix_intelligence_alerts_type'), 'intelligence_alerts', ['type'], unique=False)
    op.create_table('investment_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('need_cluster_id', sa.Uuid(), nullable=False),
    sa.Column('government_project_id', sa.Uuid(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['government_project_id'], ['government_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['need_cluster_id'], ['need_clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_matches_government_project_id'), 'investment_matches', ['government_project_id'], unique=False)
    op.create_index(op.f('ix_investment_matches_need_cluster_id'), 'investment_matches', ['need_cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_matches_need_cluster_id'), table_name='investment_matches')
    op.drop_index(op.f('ix_investment_matches_government_project_id'), table_name='investment_matches')
    op.drop_table('investment_matches')
    op.drop_index(op.f('ix_intelligence_alerts_type'), table_name='intelligence_alerts')
    op.drop_index(op.f('ix_intelligence_alerts_status'), table_name='intelligence_alerts')
    op.drop_index(op.f('ix_intelligence_alerts_severity'), table_name='intelligence_alerts')
    op.drop_index(op.f('ix_intelligence_alerts_need_cluster_id'), table_name='intelligence_alerts')
    op.drop_index(op.f('ix_intelligence_alerts_government_project_id'), table_name='intelligence_alerts')
    op.drop_table('intelligence_alerts')
    op.drop_index(op.f('ix_need_clusters_status'), table_name='need_clusters')
    op.drop_index(op.f('ix_need_clusters_priority_score'), table_name='need_clusters')
    op.drop_index(op.f('ix_need_clusters_location_name'), table_name='need_clusters')
    op.drop_index(op.f('ix_need_clusters_category'), table_name='need_clusters')
    op.drop_table('need_clusters')
    op.drop_index(op.f('ix_government_projects_status'), table_name='government_projects')
    op.drop_index(op.f('ix_government_projects_location'), table_name='government_projects')
    op.drop_index(op.f('ix_government_projects_category'), table_name='government_projects')
    op.drop_table('government_projects')
    # ### end Alembic commands ###
