"""add_analytics_snapshot_and_anomaly

Revision ID: 3aec9843a868
Revises: f7a8b9c0d1e2
Create Date: 2026-08-14 15:20:19.523174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aec9843a868'
down_revision: Union[str, None] = 'f7a8b9c0d1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('total_grievances', sa.Integer(), nullable=False),
    sa.Column('open_grievances', sa.Integer(), nullable=False),
    sa.Column('closed_grievances', sa.Integer(), nullable=False),
    sa.Column('sla_breaches', sa.Integer(), nullable=False),
    sa.Column('escalated_grievances', sa.Integer(), nullable=False),
    sa.Column('average_resolution_hours', sa.Float(), nullable=False),
    sa.Column('average_assignment_hours', sa.Float(), nullable=False),
    sa.Column('average_acknowledgement_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operational_anomalies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('anomaly_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operational_anomalies')
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###
