"""create_grievance_embedding_and_priority_fields

Revision ID: 5b44d2158d6d
Revises: 83e3c24e8510
Create Date: 2026-08-14 14:03:52.121995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '5b44d2158d6d'
down_revision: Union[str, None] = '83e3c24e8510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grievance_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grievance_id', sa.Uuid(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grievance_embeddings_grievance_id'), 'grievance_embeddings', ['grievance_id'], unique=True)
    op.execute("CREATE INDEX idx_grievance_embeddings_hnsw ON grievance_embeddings USING hnsw (embedding vector_cosine_ops);")
    op.add_column('grievances', sa.Column('priority_score', sa.Float(), nullable=True))
    op.add_column('grievances', sa.Column('priority_signals', sa.JSON(), nullable=True))
    op.add_column('grievances', sa.Column('priority_explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grievances', 'priority_explanation')
    op.drop_column('grievances', 'priority_signals')
    op.drop_column('grievances', 'priority_score')
    op.drop_index(op.f('ix_grievance_embeddings_grievance_id'), table_name='grievance_embeddings')
    op.drop_table('grievance_embeddings')
    # ### end Alembic commands ###
