"""add_governance_engine

Revision ID: be6cbff5b159
Revises: 5b44d2158d6d
Create Date: 2026-08-14 20:07:45.973531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6cbff5b159'
down_revision: Union[str, None] = '5b44d2158d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sla_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'priority', name='uq_department_priority_sla')
    )
    op.create_table('accountability_dossiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('grievance_id', sa.Uuid(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grievance_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('grievance_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('grievances', sa.Column('escalated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('grievances', sa.Column('escalation_level', sa.Integer(), server_default='0', nullable=False))
    op.add_column('grievances', sa.Column('risk_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('grievances', sa.Column('risk_factors', sa.JSON(), nullable=True))
    op.add_column('grievances', sa.Column('risk_calculated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grievances', 'risk_calculated_at')
    op.drop_column('grievances', 'risk_factors')
    op.drop_column('grievances', 'risk_score')
    op.drop_column('grievances', 'escalation_level')
    op.drop_column('grievances', 'escalated')
    op.drop_table('notifications')
    op.drop_table('accountability_dossiers')
    op.drop_table('sla_policies')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
